import {Geist, Geist_Mono} from "next/font/google";
import {Analytics} from '@vercel/analytics/next';
import "./globals.css";
import store from "@/redux/store";
import {Provider} from "react-redux";
import React from "react";
import ReduxWrapper from "@/components/ReduxWrapper";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <ReduxWrapper>
            {children}
            <Analytics/>
        </ReduxWrapper>

        </body>
        </html>
    );
}
